language: python
python:
- '3.6'
sudo: required
dist: trusty
branches:
  only:
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install:
- make install-deps
script:
- make build VERSION=$TRAVIS_TAG
deploy:
- provider: pypi
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
  username: phoenix.lv
  password:
    secure: qvOHhsdn3qZV/J70Hm39Uy6V5UvUbDlEkZxB3Bb/ICYOdzXLZVxGQGIZDAVTX8DX+FSck9gL5j7xN0kXcxwYcIj3L3mcpYYxiQsAoIrnzk/sFQAByz9GKF5ck7xfZkbEi4eX6dqNVNgY2bFPvFo2+ktJeCFHw1qpyUIgYPb2PVj8qXTrtWkePeNLWC7ORVvxwA/Ky0YMIIwWogTzT0UC4vsZ6lAvuLdZvUPwPR7Z4olLTRqmFIAH66Jzq30T5lpQKQO1J4bO2A8qPLnbVwk5PSvE5rXT2YwLPkXGUCzBCUUzLNwojxhtdWXm7gN3bLdwpH1/XQhHgf5HP++XHMHBF+K9ieCTlmE6gYMFutzXaVpS/f8Ywn95wfak1KoSeeSwAK1NE3f9e0Ck4kJb7MylLwOII8RPIWlBjnVVQfe5nqFxWXyh8SAxu9HTvo4OUaWFFoAqm/aCSflHlJI6MGF/ZuPfYm17X8sdxRGkLzXLFdAFWnr2aIIGctjBRLgEH5hR8jWzEeJWkiP7LFz+4yGOrIEO9qJsJHEtreS90O6phJH0QO+OkZgc4OciH4yCwn3/YBhWICd2oU6LSr1zNdLD6Wp5yb89Hg75kGbDR4P8kkmPCr9nlKbmyZrgG7KN+Shi6IfhC+xfhw/Y4rsdD1znCq2CLmDb6F3F22mriUdCus8=
